server:
  port: 808
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/campus?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true
      username: root
      password: 123456
   jpa:
     generate-ddl: true
     show-sql: true